---
title: "Blog Ten"
author: "Jackson Delgado"
date: '2022-12-05'
output: md_document
---

# Blog Post Ten: Campaign Narrative

### December 5, 2022

[Back to Homepage](../../README.md)

## Introduction 

In this blog post, I will analyze the results of the 2022 midterm election in __Connecticut's 5th district__, a district of particular interest to me as it is the most competitive district in my home state. I will compare the actual election results to the district's forecast, and then turn to the story of the district's campaign to explain the discrepancy. 

## CT-05 Introduction

[CT-05](https://ballotpedia.org/Connecticut%27s_5th_Congressional_District) is the northwestern-most congressional district in the state. It runs along the border of New York state on the top and left, extends to (but does not include) the Connecticut state capital Hartford on the right, and reaches its bottom just before the cities and towns along Interstate 95. The district mostly contains suburban areas, however it also contains sections of the state's smaller cities: New Britain, Danbury, Waterbury, and Torrington. The district's boundaries were only slightly revised by redistricting after the 2020 census. 

The district is majority (just over two-thirds, in fact) white, but there is a sizable Hispanic population as well (just over one-fifth of the district). All other racial and ethnic groups make up less than ten percent of the district. The district is somewhat middle-of-the-pack economically, with a median household income of just over \$75,000 (compared to a nationwide median household income of around \$71,000). The gender balance of the district skews slightly towards women, with 48.8\% men and 51.2\% women. 

This district has been represented by a Democrat since 2006, when Chris Murphy (one of the current senators of the state) defeated Republican incumbent Nancy Johnson. Since then, the district has been safely Democratic: Elizabeth Etsy represented the district from the 2012 election (when Chris Murphy won his seat in the Senate) until the 2018 election, when she did not seek re-election and current incumbent Jahana Hayes won the seat. These elections were each decided by at least four points, and often by a much wider margin. It was not until the 2022 midterm election that this district became competitive. 

In the 2022 election, incumbent Democrat [Jahana Hayes](https://hayes.house.gov/about) ran against Republican challenger [George Logan](https://ctsenaterepublicans.com/about-logan/). Both Hayes and Logan are natives of the district. Hayes grew up in poverty, and attributes her success to education - indeed, she holds degrees from Naugatuck Valley Community College, Southern Connecticut State University, the University of Saint Joseph, and the University of Bridgeport, and was a high school history teacher for fifteen years. She rose to the national stage in 2016 when she was named National Teacher of the Year, and the subsequent year in this role (traveling the country to promote public education) allowed her to begin her political career with her seat win in the 2018 election. Logan, on the other hand, served as a state senator since the 2016 election, and hoped to make the jump to Congress in the 2022 election. He holds engineering degrees from Trinity College and the University of Bridgeport, and worked on the business side of Connecticut's largest private water company for many years, while also getting involved with many community-based and volunteer organizations in the area.

## 2022 Election Recap

On November 8, Hayes ultimately survived Logan's bid for her seat, but by an incredibly close margin. She won __50.4\%__ of the two-party vote share, with Logan taking __49.6\%__. This amounted to a difference of just 1842 votes, and was by far the closest electoral margin of the district in the past two decades. 

The district-level component of our [final model](https://jrdelgado2018.github.io/GOV1347/blogs/blog8/Blog-Eight.html) predicted that Hayes would receive __54.4\%__ of the two-party vote share, based on expert ratings from [Inside Elections](https://insideelections.com/ratings/house) and the [Cook Political Report](https://www.cookpolitical.com/ratings/house-race-ratings), demographic data, the incumbent's ideological positioning as measured by DW-NOMINATE scores, and structural election factors. This correctly predicted Hayes' victory, but overpredicted how well she would do by four points. 

However, the expert forecasts from Cook and Inside Elections (that were used in our model) predicted both the direction and magnitude of this race quite accurately - they both rated the district as a toss-up that leaned Democrat. And the [most recent polls in the district](https://projects.fivethirtyeight.com/polls/house/2022/connecticut/5/) (that were not considered in our final model) predicted that Hayes would win __50.7\%__ of the two-party vote, which is only 0.3 points of an overshoot from the true vote share. 

For this district, we actually could have made a more accurate prediction had we simply predicted what Cook/Inside Elections said, or simply predicted what the most recent polls said. So, as we examine the campaign of Connecticut's 5th district, we have two items to think about. First, what about the campaign made the final outcome so reflective of the polls/expert predictions? Second, what might have caused our final forecast to inflate Hayes' success? We will also think about what changed in this election that made it so much more competitive than previous cycles. 

## The Campaign

Over the summer of 2022, the race in Connecticut's 5th district began to attract nationwide attention after it was designated as a toss-up by many political experts. The Republican Party took this as a positive sign for Logan's chances, [funneling hundreds of thousands of dollars into an independent air war](https://ctmirror.org/2022/07/15/jahana-hayes-money-lead-over-george-logan-in-toss-up-ct-district-5-race/) but not directly into Logan's campaign war chest. On the other hand, Hayes [raised more than three times as much money as Logan](https://ctmirror.org/2022/07/15/jahana-hayes-money-lead-over-george-logan-in-toss-up-ct-district-5-race/), with her campaign emphasizing the idiosyncrasy of CT-05's voters as opposed to Logan's strategy of riding the hoped-for nationwide "red wave." Indeed, the [air war content of the campaigns reflect this dichotomy of approaches.](https://ctmirror.org/2022/08/31/hayes-logan-ads-5th-district-election/). Republican super PACs ran ads [criticizing Hayes for aligning with the Democrats' economic policies](https://ctmirror.org/2022/08/31/hayes-logan-ads-5th-district-election/), implicating her in the nationwide period of high inflation and slow recovery from COVID. On the other hand, Hayes' campaign [hammered home threats to a woman's right to choose](https://ctmirror.org/2022/08/31/hayes-logan-ads-5th-district-election/), knowing that the district (and the state at large) has overwhelmingly high support of abortion despite more mixed views on other policy divisions. 

As the air war intensified, pitting Logan's criticism of the Democrats' handling of the economy against Hayes' fears of the Republicans imposing a nationwide abortion ban, national attention to CT-05 grew when [Vice President Harris visited the district for a talk at Central Connecticut State University](https://www.wshu.org/connecticut-news/2022-10-06/connecticuts-5th-district-congressional-race-draws-national-attention) in early October. Although this was not an official campaign event, Harris used the event to [support Hayes' re-election campaign](https://www.wshu.org/connecticut-news/2022-10-06/connecticuts-5th-district-congressional-race-draws-national-attention), emphasizing the risks to abortion access that the overturning of Roe v. Wade created. Logan countered this appearance by [emphasizing his support for abortion given certain restrictions](https://www.wshu.org/connecticut-news/2022-10-06/connecticuts-5th-district-congressional-race-draws-national-attention), and turning the focus of the campaign back towards the economy, but Hayes [questioned his pro-choice beliefs given his loyalty to the Republican Party](https://www.fox61.com/article/news/politics/elections/competition-tightens-in-connecticuts-5th-district/520-9f498ca6-858a-4a66-acae-c461d01fa76e). Even with [both candidates being pro-choice](https://www.fox61.com/article/news/politics/elections/competition-tightens-in-connecticuts-5th-district/520-9f498ca6-858a-4a66-acae-c461d01fa76e), Hayes attempted to inflate the importance of the issue by presenting herself as much more committed to it than Logan, whereas Logan attempted to deflate the importance of the issue by presenting himself as pro-choice enough that the economy should be the larger factor in the head of a voter. 

By the end of October/early November, [outside spending on the race exceeded seven million dollars](https://ctmirror.org/2022/10/24/ct-5th-district-election-race-jahana-hayes-george-logan/). While access to abortion vs. the state of the economy [continued to be the primary focus of the campaign](https://ctmirror.org/2022/10/24/ct-5th-district-election-race-jahana-hayes-george-logan/), the two candidates began to shift their focus towards secondary issues in last-ditch efforts to win voters. An early November campaigning event where Hayes was joined by popular Senator Chris Murphy saw the two [talk about Medicare and social security](https://www.nbcconnecticut.com/decision-2022/high-stakes-for-connecticuts-5th-congressional-district-race/2907078/), emphasizing the Democrat's commitment to the two programs. Logan, on the other hand, countered by dismissing his opposition to the programs, and [emphasizing the importance of Republican representation](https://www.nbcconnecticut.com/decision-2022/high-stakes-for-connecticuts-5th-congressional-district-race/2907078/) for a state that has not sent a Republican to Congress in almost two decades. As Election Day approached, the two candidates kept up campaign pressure, knowing that the vote would be a close one. 

## Explaining Forecast Deviations

With the story of this campaign in mind, we can now answer the questions that we set out to answer. 

First of all, it becomes clear why this race was so much closer than CT-05 races have been in previous cycles. This is a district that was hit [particularly hard by the economic difficulties of the past couple years](https://www.washingtonpost.com/politics/2022/11/05/biden-voting-district-could-send-connecticuts-first-republican-congress-decade/). The suburbs and urban areas of the district were built around manufacturing facilities, many of which are long gone, so [voters care a lot about affordability and job creation](https://www.washingtonpost.com/politics/2022/11/05/biden-voting-district-could-send-connecticuts-first-republican-congress-decade/). This key issue points decidedly away from the Democrats, unlike when Hayes was first running for office. Moreover, this campaign centered much less around candidate quality than previous elections. When Hayes first ran for office, her campaign [centered around education and her impressive achievements within that field](https://www.washingtonpost.com/politics/2022/11/05/biden-voting-district-could-send-connecticuts-first-republican-congress-decade/), justifying her foray into politics (without any formal experience) by her one-of-a-kind background. Her focus on this issue allowed her to present herself to voters as a high-quality candidate. As we saw this time around, though, Hayes' campaign was driven primarily by her commitment to access to abortion and less by her impressive background. Logan also emphasized the [need for ideological change](https://www.washingtonpost.com/politics/2022/11/05/biden-voting-district-could-send-connecticuts-first-republican-congress-decade/) as opposed to his background in industry and the state senate, knowing that while also impressive, his quality likely would not have been perceived by voters as highly as Hayes's. All in all, we see that this election stripped Hayes of her ability to make an economic appeal to voters, and of her predisposition to make appeals based on her quality as a candidate, which severely loosened the hold that Democrats had on this district. 

Given this reasoning for the closeness of the race, [Vavreck's analysis of effective and ineffective campaigns](https://www.jstor.org/stable/j.ctt7t1g4) almost perfectly explains the story of the district. Vavreck posits that when the economy is in a negative state, the challenger should run a "clarifying" campaign that highlights the state of the economy as a need for change, and the incumbent should run an "insurgent" campaign that highlights the most favorable possible ideological divide between the two candidates. And this is almost exactly what we saw in CT-05. Logan and the Republicans ran a prototypical clarifying campaign, using an air war of millions of dollars to hammer home the Democrats' (and by association, Hayes') culpability in leaving the largely working-class district (and the country at-large) in a poor economic situation. On the other hand, Hayes' and the Democrats ran a campaign that emphasized the threats to a woman's right to choose, recognizing that a district with a large female presence and a large Hispanic presence would find this issue particularly salient. While we did see the two candidates address secondary issues in their campaigns, the primary messaging adhered almost perfectly to Vavreck's prescription of an effective campaign. This explains why the experts were able to so accurately forecast the race - they saw the adherence of the campaigns to their "optimal" strategies and were then able to reason that the overall race would look like a tug of war between almost equally matched opponents. We can also see why the district polls were able to so accurately forecast this race - in such a campaign-driven race, the polls adequately captured the campaign messaging that was resonating with the different voters in the district. 

Given Vavreck's analysis, we can also see why our final forecast overshot the vote share that Hayes would achieve. As we hypothesized in the [reflection of our final model](https://jrdelgado2018.github.io/GOV1347/blogs/blog9/Blog-Nine.html), our forecast suffered from the lack of inclusion of a measure of campaigning and the air war. We observed that when this factor was included in a previous blog post, the effect tended to be negative for the Democrats - in other words, that a larger air war should deflate our expectations for how well the Democrat would do. The race in CT-05 was no exception - it was the *campaign* that made a formerly solid district so competitive this year. So, had we included a term in our model that measured the effect of campaigning and the air war, our confidence in Hayes would have been dampened, more adequately reflecting Vavreck's predictions for this race. To conclude, we learned something very valuable from this experience: that campaigns *matter*.
